variables:
 DBB_HOME: "/usr/lpp/IBM/dbb"
Build:
 script:
#  - mkdir -p /u/ibmuser/$CI_PROJECT_DIR/BUILD-$CI_PIPELINE_ID
 - echo $CI_PROJECT_DIR 
 - echo BUILD-$CI_PIPELINE_ID
 - $DBB_HOME/bin/groovyz -Djava.library.path=$DBB_HOME/lib:/usr/lib/java_runtime64 build.groovy --workspace /u/ibmuser/$CI_PROJECT_DIR/samples --hlq GITLAB.ZAPP.CLEAN.MAIN --workDir /u/ibmuser/$CI_PROJECT_DIR/BUILD-$CI_PIPELINE_ID --application MortgageApplication --logEncoding UTF-8 --fullBuild --verbose
 - $DBB_HOME/bin/groovyz Pipeline/CreateUCDComponentVersion/dbb-ucd-packaging.groovy --buztool /u/ibmuser/ibm-ucd/agent/bin/buztool.sh --workDir /u/ibmuser/$CI_PROJECT_DIR/BUILD-$CI_PIPELINE_ID/ --component MYCOMP --propertyFile /u/ibmuser/ibm-ucd/agent/conf/applicationRepositoryProps.properties --versionName MyVersion

variables:
 CI_DEBUG_TRACE: "true"