variables:
    DBB_HOME: "/usr/lpp/IBM/dbb"
    CI_DEBUG_TRACE: "true"
#     ZAPPBUILD: $CI_PROJECT_DIR/dbb-zappbuild
#     HLQ: "GITLAB.CATMAN"
#     applicationName: "$CI_PROJECT_NAME"
#     UCD_APPLICATION: "CatalogManager"
#     UCD_COMPONENT: "CatalogManager"
# #    artifactoryConfig: "/var/ucd-agent/conf/artifactory/CatalogManager.artifactory.properties"
#     CONFIG_ARTIFACTORY: "${CI_PROJECT_DIR}/${CI_PROJECT_NAME}/application-conf/artifactory.properties"
#     CONFIG_REPOSITORY_INFO: "${CI_PROJECT_DIR}/${CI_PROJECT_NAME}/application-conf/repositoryInfo.properties"
#     CONFIG_CODE_REVIEW: "${CI_PROJECT_DIR}/${CI_PROJECT_NAME}/application-conf/codeReview.properties"
#     PROPERTY_GROUP_FILE: "${CI_PROJECT_DIR}/${CI_PROJECT_NAME}/application-conf/property-group.xml"

stages:
    - Build
    - Package
    - Deploy

Build:
    stage: Build
    script:
        - $DBB_HOME/bin/groovyz -Djava.library.path=$DBB_HOME/lib:/usr/lib/java_runtime64 build.groovy --workspace /u/ibmuser/$CI_PROJECT_DIR/samples --hlq GITLAB.ZAPP.CLEAN.MAIN --workDir /u/ibmuser/$CI_PROJECT_DIR/BUILD-$CI_PIPELINE_ID --application MortgageApplication --logEncoding UTF-8 --fullBuild --verbose

Package:
    stage: Package
    variables:
        GIT_STRATEGY: none
        GIT_CHECKOUT: "false"
    script:
        # - $DBB_HOME/bin/groovyz Pipeline/CreateUCDComponentVersion/dbb-ucd-packaging.groovy --buztool /u/ibmuser/ibm-ucd/agent/bin/buztool.sh --workDir /u/ibmuser/$CI_PROJECT_DIR/BUILD-$CI_PIPELINE_ID --component MYCOMP --propertyFile /u/ibmuser/ibm-ucd/agent/conf/applicationRepositoryProps.properties --versionName $CI_COMMIT_REF_NAME-$CI_PIPELINE_ID --pipelineURL https://gitlab.com/ibm65/dbb-zappbuild/-/ci/pipelines/$CI_PIPELINE_ID --ucdV2PackageFormat
        - $DBB_HOME/bin/groovyz Pipeline/CreateUCDComponentVersion/dbb-ucd-packaging.groovy --buztool /u/ibmuser/ibm-ucd/agent/bin/buztool.sh --workDir /u/ibmuser/$CI_PROJECT_DIR/BUILD-$CI_PIPELINE_ID --component MYCOMP --propertyFile /u/ibmuser/ibm-ucd/agent/conf/applicationRepositoryProps.properties --versionName $CI_COMMIT_REF_NAME-$CI_PIPELINE_ID 

Deploy:
    stage: Deploy
    variables:
        GIT_STRATEGY: none
        GIT_CHECKOUT: "false"
    script:
        - export JAVA_HOME=/javasc/J11.0_64
        - echo $JAVA_HOME
        - $DBB_HOME/bin/groovyz Pipeline/DeployUCDComponentVersion/ucd-deploy.groovy  -a "MortgageApplication" -e "test-application-environment" -U admin -P thor13 -u https://169.62.42.236:8443 -d "MortgageApplication:latest" -p Deploy -s TLSv1.2 -v
