variables:
 DBB_HOME: "/usr/lpp/dbb/v1r0"
Build:
 script:
 - mkdir -p $CI_PROJECT_DIR/BUILD-$CI_PIPELINE_ID
 - $DBB_HOME/bin/groovyz -Djava.library.path=$DBB_HOME/lib:/usr/lib/java_runtime64 build.groovy --workspace $CI_PROJECT_DIR/samples --hlq GITLAB.ZAPP.CLEAN.MAIN --workDir $CI_PROJECT_DIR/BUILD-$CI_PIPELINE_ID --application MortgageApplication --logEncoding UTF-8 --fullBuild --verbose
variables:
 CI_DEBUG_TRACE: "true"