variables:
    DBB_HOME: "/usr/lpp/IBM/dbb"
    CI_DEBUG_TRACE: "true"
#     ZAPPBUILD: $CI_PROJECT_DIR/dbb-zappbuild
#     HLQ: "GITLAB.CATMAN"
#     applicationName: "$CI_PROJECT_NAME"
#     UCD_APPLICATION: "CatalogManager"
#     UCD_COMPONENT: "CatalogManager"
# #    artifactoryConfig: "/var/ucd-agent/conf/artifactory/CatalogManager.artifactory.properties"
#     CONFIG_ARTIFACTORY: "${CI_PROJECT_DIR}/${CI_PROJECT_NAME}/application-conf/artifactory.properties"
#     CONFIG_REPOSITORY_INFO: "${CI_PROJECT_DIR}/${CI_PROJECT_NAME}/application-conf/repositoryInfo.properties"
#     CONFIG_CODE_REVIEW: "${CI_PROJECT_DIR}/${CI_PROJECT_NAME}/application-conf/codeReview.properties"
#     PROPERTY_GROUP_FILE: "${CI_PROJECT_DIR}/${CI_PROJECT_NAME}/application-conf/property-group.xml"

stages:
    - Build
    - Package

Build:
    stage: Build
    script:
        - mkdir -p /u/ibmuser/$CI_PROJECT_DIR/BUILD-OUTPUT
        - $DBB_HOME/bin/groovyz -Djava.library.path=$DBB_HOME/lib:/usr/lib/java_runtime64 build.groovy --workspace /u/ibmuser/$CI_PROJECT_DIR/samples --hlq GITLAB.ZAPP.CLEAN.MAIN --workDir /u/ibmuser/$CI_PROJECT_DIR --application MortgageApplication --logEncoding UTF-8 --fullBuild --verbose

Package:
    stage: Package
    variables:
        GIT_STRATEGY: none
        GIT_CHECKOUT: "false"
    script:
        - $DBB_HOME/bin/groovyz Pipeline/CreateUCDComponentVersion/dbb-ucd-packaging.groovy --buztool /u/ibmuser/ibm-ucd/agent/bin/buztool.sh --workDir /u/ibmuser/$CI_PROJECT_DIR --component MYCOMP --propertyFile /u/ibmuser/ibm-ucd/agent/conf/applicationRepositoryProps.properties --versionName MyVersion