openapi: 3.0.0
info:
  title: CatalogManagerApi
  description: Manage a catalog through an API for CICS.
  version: '1.1'
  license:
    name: Apache-2.0
    url: https://opensource.org/licenses/Apache-2.0
servers:
- url: /
security:
  - BasicAuth: []
  - BearerAuth: []
paths:
  /phoneapi/items:
    get:
      tags:
        - Catalog
      summary: Get items in the catalog
      description: Uses the catalogProgram CICS COMMAREA z/OS asset
      operationId: getPhoneList
      # parameters:
      #   - $ref: '#/components/parameters/'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /phoneapi/items/{itemID}:
    get:
      tags:
        - Catalog
      summary: Get an item from the catalog
      description: Uses the catalogProgram CICS COMMAREA z/OS asset
      operationId: getPhoneSingle
      parameters:
        - $ref: '#/components/parameters/itemID'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogItemResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Item could not be found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: A message describing the error
  # /orders:
  #   post:
  #     tags:
  #       - Catalog
  #     summary: Place an order for an item
  #     description: Uses the catalogProgram CICS COMMAREA z/OS asset
  #     operationId: ordersPost
  #     parameters:
  #       - $ref: '#/components/parameters/itemNumber'
  #       - $ref: '#/components/parameters/quantity'
  #     responses:
  #       '200':
  #         description: OK
  #         content:
  #           application/json:
  #             schema:
  #               type: object
  #               properties:
  #                 message:
  #                   type: string
  #       '400':
  #         description: Bad Request
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/ErrorResponse'
  #       '500':
  #         description: Internal Server Error
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
      example:
        message: A message describing the error
    CatalogResponse:
      type: object
      properties:
        cics_cat_resp:
          type: object
          properties:
            inquire_request:
              type: object
              properties:
                cat_item:
                  type: array
                  items:
                    type: object
                    properties:
                      itemID:
                        type: integer
                        minimum: 0
                        maximum: 9999
                      description:
                        type: string
                        maxLength: 40
                      cost:
                        type: string
                        maxLength: 6
                      department:
                        type: integer
                        minimum: 0
                        maximum: 999
                      in_stock:
                        type: integer
                        minimum: 0
                        maximum: 9999
                      on_order:
                        type: integer
                        minimum: 0
                        maximum: 999
    CatalogItemResponse:
      type: object
      properties:
        cics_single_resp:
          type: object
          properties:
            inquire_single:
              type: object
              properties:
                single_item:
                  type: object
                  properties:
                    itemID:
                      type: integer
                      minimum: 0
                      maximum: 9999
                    description:
                      type: string
                      maxLength: 40
                    cost:
                      type: string
                      maxLength: 6
                    department:
                      type: integer
                      minimum: 0
                      maximum: 999
                    in_stock:
                      type: integer
                      minimum: 0
                      maximum: 9999
                    on_order:
                      type: integer
                      minimum: 0
                      maximum: 999

  parameters:
    itemID:
      name: itemID
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    startItemID:
      name: startItemID
      in: query
      required: true
      style: form
      explode: true
      schema:
        type: string
    itemNumber:
      name: itemNumber
      in: query
      required: true
      style: form
      explode: true
      schema:
        type: string
    quantity:
      name: quantity
      in: query
      required: true
      style: form
      explode: true
      schema:
        type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
