version: "3.2"
services:
    zosConnect:
        image: icr.io/zosconnect/ibm-zcon-designer:3.0.68
        environment:
            - CICS_USER=ibmuser
            - CICS_PASSWORD={aes}AMvSBDDV8BrdbD5ppecAo3BFuf5uEwjRTu5rADfK5t+w
            - CICS_HOST=169.59.167.206
            - CICS_PORT=29555
            - HTTP_PORT=9090
        ports:
            - "9443:9443"
            - "9080:9080"
        volumes:
            - ./CatalogManagerApi:/workspace/project
            - ./logs/:/logs/
            - ./certs:/config/resources/security/:ro
